services:
    schachbulle.translation_fields.service.languages:
        class: Schachbulle\TranslationFieldsBundle\Service\Languages
        public: true

    schachbulle.translation_fields.service.translator:
        class: Schachbulle\TranslationFieldsBundle\Service\Translator
        public: true
